"""
AP Framework World for Archipelago.

This is a template/base world for games using the AP Framework mod system.
It dynamically creates items and locations from a capabilities config
generated by the in-game framework and embedded in the YAML as base64.

To create a game-specific world:
1. Copy this directory to your Archipelago/worlds/<game_name> folder
2. Update the game name and other constants
3. Optionally override methods to add game-specific logic
"""

from typing import Dict, Any, ClassVar, Set
import base64
import json

from BaseClasses import Item, Location, Region, Tutorial, ItemClassification, MultiWorld
from worlds.AutoWorld import World, WebWorld

from .Items import APFrameworkItem, ItemData, build_item_table, get_filler_items, get_trap_items
from .Locations import APFrameworkLocation, LocationData, build_location_table
from .Logger import APFLogger
from .LogicParser import is_always_false
from .Options import APFrameworkOptions
from .Rules import set_rules, set_completion_rules


# Maximum items+locations per APF configuration. Each player slot gets an
# exclusive ID range of this size so two APF players never collide.
PER_PLAYER_RANGE = 50_000


class APFrameworkWebWorld(WebWorld):
    """Web world for displaying game info on the Archipelago website."""
    theme = "jungle"

    tutorials = [
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to setting up the AP Framework multiworld.",
            "English",
            "setup_en.md",
            "setup/en",
            ["AP Framework Team"]
        )
    ]


class APFrameworkWorld(World):
    """
    AP Framework World - A template for games using the AP Framework mod system.

    This world reads item and location definitions from a capabilities config
    embedded as base64 in the YAML, allowing any game with AP Framework
    mods to be randomized in Archipelago.
    """

    # =========================================================================
    # Class Variables - Override these in game-specific subclasses
    # =========================================================================

    game: ClassVar[str] = "APFramework"  # Change to your game's name
    web: ClassVar[WebWorld] = APFrameworkWebWorld()

    options_dataclass = APFrameworkOptions
    options: APFrameworkOptions

    # Topology: 0 = no logic, 1 = basic, 2 = advanced
    topology_present: ClassVar[bool] = False

    # =========================================================================
    # Instance Variables
    # =========================================================================

    item_table: Dict[str, ItemData]
    location_table: Dict[str, LocationData]
    region_table: Dict[str, str]  # region_name -> logic expression string
    capabilities: Dict[str, Any]
    id_remapping: Dict[int, int]
    log: APFLogger

    # Item/Location name to ID mappings (required by Archipelago)
    item_name_to_id: ClassVar[Dict[str, int]] = {}
    location_name_to_id: ClassVar[Dict[str, int]] = {}

    # =========================================================================
    # Initialization
    # =========================================================================

    def __init__(self, multiworld: MultiWorld, player: int):
        super().__init__(multiworld, player)
        self.item_table = {}
        self.location_table = {}
        self.region_table = {}
        self.capabilities = {}
        self.id_remapping = {}
        self.log = APFLogger()  # default warn level until generate_early

    # =========================================================================
    # World Generation
    # =========================================================================

    def generate_early(self) -> None:
        """
        Decode base64 capabilities data and set up item/location tables.
        Called before item/location creation.
        """
        # Initialize logger from YAML options
        log_level = getattr(self.options, "apf_log", None)
        log_file = getattr(self.options, "apf_logfile", None)
        self.log = APFLogger(
            min_level=log_level.current_key if log_level else "warn",
            logfile=log_file.value if log_file else "",
        )

        cap_data = self.options.capabilities_data.value
        if not cap_data:
            raise Exception(
                f"[{self.game}] capabilities_data is required.\n"
                "Use the YAML file generated by the AP Framework, or manually "
                "base64-encode your AP_Capabilities JSON file."
            )

        try:
            decoded = base64.b64decode(cap_data).decode("utf-8")
            self.capabilities = self._process_capabilities(json.loads(decoded))
        except Exception as e:
            raise Exception(f"[{self.game}] Failed to decode capabilities_data: {e}")

        # Filter capabilities by logic (option-gated entries pruned if always-false)
        self._filter_by_logic()

        # Apply item overrides (cross-mod item type changes)
        self._apply_item_overrides()

        # Build region table first so location derivation can use known_regions
        self.region_table = self._build_region_table()

        # Build item and location tables
        self.item_table = build_item_table(self.capabilities)
        known_regions = set(self.region_table.keys()) if self.region_table else None
        self.location_table = build_location_table(self.capabilities, known_regions)

        # Set topology_present based on logic mode
        if self.options.logic_mode.value == 1 and self.region_table:  # basic
            self.__class__.topology_present = True

        # Update class-level ID mappings (required for item/location creation)
        self.__class__.item_name_to_id = {
            name: data.code for name, data in self.item_table.items()
        }
        self.__class__.location_name_to_id = {
            name: data.code for name, data in self.location_table.items()
        }

        # Apply per-player ID offset so two APF players never share IDs
        self._apply_player_offset()

        # Check for ID conflicts with other worlds
        self.check_id_conflicts()

        # Update reverse mappings and network data package.
        # Archipelago snapshots the data package at module import time (when our
        # ClassVars are still {}). We must refresh it after populating the tables.
        self._update_data_package()

        # Statistics summary
        logic_str = "basic" if self.options.logic_mode.value == 1 else "none"
        self.log.info(
            f"generate_early complete: {len(self.item_table)} items, "
            f"{len(self.location_table)} locations, "
            f"{len(self.region_table)} regions, "
            f"logic_mode={logic_str}",
            "World",
        )
        goals = self.capabilities.get("goals", [])
        overrides = self.capabilities.get("item_overrides", [])
        if goals or overrides:
            self.log.info(
                f"  {len(goals)} goals, {len(overrides)} item overrides",
                "World",
            )

    def _process_capabilities(self, data: dict) -> dict:
        """Unwrap nested structure and validate."""
        # The C++ framework nests locations/items/regions/goals/item_overrides
        # under a "capabilities" key
        if "capabilities" in data and isinstance(data["capabilities"], dict):
            caps = data["capabilities"]
            if "regions" in caps:
                data["regions"] = caps["regions"]
            if "locations" in caps:
                data["locations"] = caps["locations"]
            if "items" in caps:
                data["items"] = caps["items"]
            if "goals" in caps:
                data["goals"] = caps["goals"]
            if "item_overrides" in caps:
                data["item_overrides"] = caps["item_overrides"]

        required = ["version", "game", "locations", "items", "checksum"]
        for field in required:
            if field not in data:
                raise ValueError(f"Missing required field: {field}")
        return data

    def _build_option_values(self) -> dict:
        """Build option values dict from all registered options + option_defaults fallback.

        Pass 1: Reads all options from self.options (includes both static ClassVar options
        and any dynamic mod options registered by _register_dynamic_options() at import time).
        Values are native Python types: Toggle → int 0/1, TextChoice → str, Range → int.

        Pass 2: Fallback to option_defaults from capabilities_data for any options not in
        self.options (e.g., _register_dynamic_options() skipped due to missing Players dir,
        or a new option was added to the manifest after the APWorld was last imported).
        """
        option_values: dict = {}

        # Pass 1 — all registered options (static + dynamic)
        for attr_name in dir(self.options):
            if attr_name.startswith("_"):
                continue
            opt = getattr(self.options, attr_name, None)
            if hasattr(opt, "value"):
                option_values[attr_name] = opt.value  # native type

        # Pass 2 — fallback to manifest defaults for unregistered options
        for key, defn in self.capabilities.get("option_defaults", {}).items():
            if key not in option_values:
                typ = defn.get("type", "toggle")
                raw = defn.get("default", "")
                if typ == "toggle":
                    option_values[key] = 1 if str(raw).lower() in ("true", "1", "yes") else 0
                elif typ == "range":
                    try:
                        option_values[key] = int(raw)
                    except (ValueError, TypeError):
                        option_values[key] = 0
                else:  # text_choice
                    option_values[key] = str(raw)

        return option_values

    def _filter_by_logic(self) -> None:
        """Filter capabilities entries whose logic evaluates to always-False.

        Removes locations, regions, items, and item_overrides from
        self.capabilities whose logic simplifies to False given the player's
        current option values. Prevents creating locations/items/overrides with
        never-satisfiable conditions.
        """
        option_values = self._build_option_values()

        removed_count = 0

        def _keep(entry: dict, kind: str) -> bool:
            nonlocal removed_count
            logic = entry.get("logic", "")
            if is_always_false(logic, option_values):
                self.log.debug(
                    f"Removed always-false {kind} '{entry.get('name', '?')}': {logic}",
                    "Filter",
                )
                removed_count += 1
                return False
            return True

        self.capabilities["locations"] = [
            e for e in self.capabilities.get("locations", [])
            if _keep(e, "location")]
        if "regions" in self.capabilities:
            self.capabilities["regions"] = [
                e for e in self.capabilities.get("regions", [])
                if _keep(e, "region")]
        self.capabilities["items"] = [
            e for e in self.capabilities.get("items", [])
            if _keep(e, "item")]
        if "item_overrides" in self.capabilities:
            self.capabilities["item_overrides"] = [
                e for e in self.capabilities.get("item_overrides", [])
                if _keep(e, "item_override")]
        if removed_count:
            self.log.info(
                f"logic filter: removed {removed_count} always-false entries",
                "Filter",
            )

    def _apply_item_overrides(self) -> None:
        """Apply cross-mod item type overrides.

        When Mod B declares an item_override targeting Mod A's item, the target
        item's type is changed if the override's logic condition is met.
        """
        overrides = self.capabilities.get("item_overrides", [])
        if not overrides:
            return

        option_values = self._build_option_values()

        for ovr in overrides:
            target_item = ovr.get("target_item", "")
            target_mod = ovr.get("target_mod", "")
            new_type = ovr.get("type", "")
            logic = ovr.get("logic", "")

            if not target_item or not new_type:
                continue

            # Check if logic condition is satisfied (option-only logic)
            if logic and is_always_false(logic, option_values):
                self.log.debug(
                    f"Override skipped: '{target_item}' (logic not met: {logic})",
                    "Override",
                )
                continue  # Condition not met — skip this override

            # Find and modify the target item in capabilities
            found = False
            for item in self.capabilities.get("items", []):
                name_match = item.get("name", "") == target_item
                mod_match = not target_mod or item.get("mod_id", "") == target_mod
                if name_match and mod_match:
                    old_type = item.get("type", "?")
                    item["type"] = new_type
                    found = True
                    self.log.info(
                        f"Item override: '{target_item}' {old_type} -> {new_type} "
                        f"(by {ovr.get('source_mod', 'unknown')})",
                        "Override",
                    )

            if not found:
                source = ovr.get("source_mod", "unknown")
                target_desc = f"'{target_item}'"
                if target_mod:
                    target_desc += f" (mod: {target_mod})"
                self.log.error(
                    f"Item override failed: {target_desc} not found in capabilities "
                    f"(declared by {source}). Check target_item/target_mod spelling.",
                    "Override",
                )

    def _build_region_table(self) -> Dict[str, str]:
        """Build region table from capabilities regions data.

        Returns:
            Dict mapping region name to logic expression string.
            Logic is already OR-merged by the C++ capabilities config
            when multiple mods contribute to the same region.
        """
        region_table: Dict[str, str] = {}

        for region_data in self.capabilities.get("regions", []):
            name = region_data["name"]
            logic = region_data.get("logic", "")
            region_table[name] = logic

        return region_table

    def _update_data_package(self) -> None:
        """Update reverse mappings and network data package.

        Archipelago builds the network data package at module import time from
        class-level item_name_to_id and location_name_to_id. Since this world
        populates those dynamically in generate_early(), we must update the
        pre-built data package to reflect the actual mappings.
        """
        # Update reverse mappings (used by Archipelago internals)
        self.__class__.item_id_to_name = {
            code: name for name, code in self.__class__.item_name_to_id.items()
        }
        self.__class__.location_id_to_name = {
            code: name for name, code in self.__class__.location_name_to_id.items()
        }

        # Rebuild and replace the pre-built network data package entry
        import worlds
        worlds.network_data_package["games"][self.game] = self.__class__.get_data_package_data()

        dp = worlds.network_data_package["games"][self.game]
        self.log.debug(
            f"Data package updated: {len(dp.get('item_name_to_id', {}))} items, "
            f"{len(dp.get('location_name_to_id', {}))} locations, "
            f"checksum={dp.get('checksum', 'N/A')}",
            "DataPackage",
        )

    def _apply_player_offset(self) -> None:
        """Assign unique IDs per player slot by adding a per-player offset.

        Player 1: base IDs unchanged (e.g. Key A = 6942079)
        Player 2: base + 50,000  (e.g. Key A = 6992079)
        Player 3: base + 100,000, etc.

        Stores forward remap (local→AP) in self.id_remapping for slot_data.
        Player 1 skips this (identity mapping, no slot_data overhead).
        """
        if self.player <= 1:
            return  # Player 1 uses base IDs unchanged

        offset = (self.player - 1) * PER_PLAYER_RANGE
        remap: Dict[int, int] = {}

        new_items: Dict[str, Any] = {}
        for name, data in self.item_table.items():
            new_id = data.code + offset
            remap[data.code] = new_id
            new_items[name] = data._replace(code=new_id)
        self.item_table = new_items

        new_locs: Dict[str, Any] = {}
        for name, data in self.location_table.items():
            new_id = data.code + offset
            remap[data.code] = new_id
            new_locs[name] = data._replace(code=new_id)
        self.location_table = new_locs

        self.id_remapping = remap
        self.__class__.item_name_to_id = {n: d.code for n, d in self.item_table.items()}
        self.__class__.location_name_to_id = {n: d.code for n, d in self.location_table.items()}
        self._update_data_package()

        self.log.info(
            f"Player {self.player}: applied ID offset +{offset} "
            f"({len(remap)} IDs remapped)",
            "IDOffset",
        )

    def check_id_conflicts(self) -> None:
        """Check for ID conflicts with other worlds and remap if necessary."""
        # Collect all IDs used by other worlds
        used_ids: Set[int] = set()

        for world in self.multiworld.worlds.values():
            if world.player == self.player:
                continue

            # Get location IDs
            for loc in world.multiworld.get_locations(world.player):
                if loc.address is not None:
                    used_ids.add(loc.address)

            # Get item IDs
            for item_name, item_id in getattr(world, "item_name_to_id", {}).items():
                if item_id is not None:
                    used_ids.add(item_id)

        # Check for conflicts
        my_location_ids = {data.code for data in self.location_table.values()}
        my_item_ids = {data.code for data in self.item_table.values()}
        my_ids = my_location_ids | my_item_ids

        conflicts = my_ids & used_ids

        if conflicts:
            self.remap_ids(conflicts, used_ids)

    def remap_ids(self, conflicting_ids: Set[int], all_used_ids: Set[int]) -> None:
        """Remap conflicting IDs to safe values."""
        # Find safe starting point
        all_my_ids = {data.code for data in self.item_table.values()}
        all_my_ids |= {data.code for data in self.location_table.values()}
        all_ids = all_used_ids | all_my_ids

        safe_start = max(all_ids) + 1000 if all_ids else self.capabilities.get("id_base", 6942067) + 100000

        # Build remapping
        remap: Dict[int, int] = {}
        for old_id in sorted(conflicting_ids):
            remap[old_id] = safe_start
            safe_start += 1

        self.id_remapping = remap

        # Apply remapping to location table (preserve all fields)
        new_location_table = {}
        for name, data in self.location_table.items():
            new_code = remap.get(data.code, data.code)
            new_location_table[name] = LocationData(
                code=new_code,
                name=data.name,
                mod_id=data.mod_id,
                instance=data.instance,
                region=data.region,
                logic=data.logic,
            )
        self.location_table = new_location_table

        # Apply remapping to item table (preserve all fields)
        new_item_table = {}
        for name, data in self.item_table.items():
            new_code = remap.get(data.code, data.code)
            new_item_table[name] = ItemData(
                code=new_code,
                name=data.name,
                classification=data.classification,
                mod_id=data.mod_id,
                count=data.count,
                logic=data.logic,
            )
        self.item_table = new_item_table

        # Update class-level mappings
        self.__class__.item_name_to_id = {
            name: data.code for name, data in self.item_table.items()
        }
        self.__class__.location_name_to_id = {
            name: data.code for name, data in self.location_table.items()
        }

        # Refresh data package with remapped IDs
        self._update_data_package()

    def create_regions(self) -> None:
        """Create regions and locations.

        When logic_mode is "basic" and regions are defined, creates proper regions
        with Menu connecting to all of them. Locations are placed into their
        designated regions. Locations without a declared region go into "Main".

        When logic_mode is "none" or no regions exist, all locations go into a
        single "Main" region (flat Sphere 0 behavior).
        """
        menu_region = Region("Menu", self.player, self.multiworld)
        self.multiworld.regions.append(menu_region)

        use_regions = (self.options.logic_mode.value == 1 and self.region_table)

        # Build region objects — always create "Main" as the default region
        regions: Dict[str, Region] = {}
        regions["Main"] = Region("Main", self.player, self.multiworld)

        if use_regions:
            for region_name in self.region_table:
                if region_name not in regions:
                    regions[region_name] = Region(region_name, self.player, self.multiworld)

        # Place locations into their target regions
        for loc_name, loc_data in self.location_table.items():
            target_region = loc_data.region if use_regions else "Main"

            # If the target region wasn't declared, create it on-the-fly
            if target_region not in regions:
                regions[target_region] = Region(target_region, self.player, self.multiworld)

            region = regions[target_region]
            location = APFrameworkLocation(
                self.player,
                loc_name,
                loc_data.code,
                region
            )
            region.locations.append(location)

        # Connect Menu to all regions (flat topology — item requirements enforce ordering)
        for region in regions.values():
            menu_region.connect(region)
            self.multiworld.regions.append(region)

        loc_count = sum(len(r.locations) for r in regions.values())
        self.log.info(
            f"Created {len(regions)} regions with {loc_count} locations",
            "Regions",
        )

    def create_item(self, name: str) -> APFrameworkItem:
        """Create an item by name. Required by Archipelago for pre-fill and similar."""
        item_data = self.item_table.get(name)
        if item_data:
            return APFrameworkItem(name, item_data.classification, item_data.code, self.player)
        return APFrameworkItem(name, ItemClassification.filler,
                               self.item_name_to_id.get(name, 0), self.player)

    def create_items(self) -> None:
        """Create items and add to item pool.

        Balances the pool so len(itempool) == len(locations):
        - Over-budget: culls lowest-priority items (trap < filler < useful).
          Never culls progression — that indicates a manifest bug.
        - Under-budget: fills remaining slots with filler/trap items.
        """
        import random

        total_locations = len(self.location_table)

        # --- Count phase ---
        # Separate fixed items (count >= 1) from filler templates (count == -1)
        fixed_items: list[tuple[str, ItemData]] = []
        filler_item_names: list[str] = []

        for item_name, item_data in self.item_table.items():
            if item_data.count == -1:
                filler_item_names.append(item_name)
            else:
                for _ in range(item_data.count):
                    fixed_items.append((item_name, item_data))

        fixed_count = len(fixed_items)
        self.log.debug(
            f"Pool budget: {fixed_count} fixed items, "
            f"{len(filler_item_names)} filler templates, "
            f"{total_locations} locations",
            "Items",
        )

        # --- Over-budget cull ---
        if fixed_count > total_locations:
            excess = fixed_count - total_locations
            self.log.warn(
                f"Over-budget by {excess}: {fixed_count} fixed items > "
                f"{total_locations} locations — culling lowest priority",
                "Items",
            )

            # Priority: trap(0) < filler(1) < useful(2) < progression(3)
            _PRIORITY = {
                ItemClassification.trap: 0,
                ItemClassification.filler: 1,
                ItemClassification.useful: 2,
                ItemClassification.progression: 3,
            }

            # Sort: lowest priority first; within same priority, highest index
            # first so we cull duplicates before unique entries
            fixed_items.sort(
                key=lambda pair: (_PRIORITY.get(pair[1].classification, 1), -pair[1].count),
            )

            culled = 0
            remaining_items: list[tuple[str, ItemData]] = []
            for name, data in fixed_items:
                if culled < excess and _PRIORITY.get(data.classification, 1) < 3:
                    self.log.warn(f"Culled item: '{name}' ({data.classification.name})", "Items")
                    culled += 1
                else:
                    remaining_items.append((name, data))

            if culled < excess:
                raise Exception(
                    f"[{self.game}] Cannot balance item pool: {excess} excess items "
                    f"but only {culled} non-progression items available to cull. "
                    f"This is a manifest configuration error."
                )

            fixed_items = remaining_items

        # --- Create fixed items ---
        prog_count = 0
        useful_count = 0
        filler_count = 0
        trap_count = 0

        for item_name, item_data in fixed_items:
            item = APFrameworkItem(
                item_name, item_data.classification, item_data.code, self.player
            )
            self.multiworld.itempool.append(item)
            if item_data.classification == ItemClassification.progression:
                prog_count += 1
            elif item_data.classification == ItemClassification.useful:
                useful_count += 1
            elif item_data.classification == ItemClassification.trap:
                trap_count += 1
            else:
                filler_count += 1

        # --- Under-budget fill ---
        remaining = total_locations - len(fixed_items)
        if remaining > 0 and filler_item_names:
            trap_chance = self.options.trap_item_chance.value / 100.0
            trap_items = get_trap_items(self.item_table)

            for _ in range(remaining):
                if trap_items and random.random() < trap_chance:
                    item_name = random.choice(trap_items)
                else:
                    item_name = random.choice(filler_item_names)

                item_data = self.item_table[item_name]
                item = APFrameworkItem(
                    item_name, item_data.classification, item_data.code, self.player
                )
                self.multiworld.itempool.append(item)
                if item_data.classification == ItemClassification.trap:
                    trap_count += 1
                else:
                    filler_count += 1

        # --- Log composition ---
        total_created = prog_count + useful_count + filler_count + trap_count
        self.log.info(
            f"Item pool: {prog_count} progression, {useful_count} useful, "
            f"{filler_count} filler, {trap_count} trap = {total_created} total "
            f"for {total_locations} locations",
            "Items",
        )

        assert total_created == total_locations, (
            f"Item pool size mismatch: {total_created} items != {total_locations} locations"
        )

    def set_rules(self) -> None:
        """Set access rules for locations."""
        set_rules(self)
        set_completion_rules(self)

    def fill_slot_data(self) -> Dict[str, Any]:
        """Return data to be sent to the client.

        Includes option_values so the C++ tracker engine can evaluate
        (Option: ...) logic expressions at runtime with the player's
        actual chosen YAML options.
        """
        slot_data: Dict[str, Any] = {
            "id_remapping":     self.id_remapping,
            "id_reverse_remap": {v: k for k, v in self.id_remapping.items()},
        }

        # Serialize option values for C++ logic evaluation (all values as strings)
        options_dict: Dict[str, str] = {
            k: str(v) for k, v in self._build_option_values().items()
        }
        slot_data["option_values"] = options_dict

        self.log.debug(
            f"fill_slot_data: player={self.player}, "
            f"{len(self.id_remapping)} ID remaps, "
            f"{len(options_dict)} options, "
            f"{len(self.__class__.item_name_to_id)} items, "
            f"{len(self.__class__.location_name_to_id)} locations",
            "SlotData",
        )
        return slot_data

    def get_filler_item_name(self) -> str:
        """Get a random filler item name."""
        filler_items = get_filler_items(self.item_table)
        if filler_items:
            import random
            return random.choice(filler_items)
        # Fallback - return first item
        if self.item_table:
            return next(iter(self.item_table.keys()))
        return "Nothing"


# =============================================================================
# Dynamic Mod Option Registration
# Runs at APWorld import time — before Archipelago parses any player YAMLs.
# =============================================================================

def _make_option_class_from_defn(key: str, defn: dict, mod_id: str = ""):
    """Return a Toggle / TextChoice / Range subclass for a mod-defined option, or None."""
    from Options import Toggle, TextChoice, Range
    typ = defn.get("type", "toggle")
    description = defn.get("description", key.replace("_", " ").title())
    default = defn.get("default", "")
    mod_tag = f" [Mod: {mod_id}]" if mod_id else ""

    if typ == "toggle":
        default_val = 1 if str(default).lower() in ("true", "1", "yes") else 0
        doc = f"{description}. (0 = off, 1 = on){mod_tag}"
        return type(f"ModOption_{key}", (Toggle,), {
            "display_name": description,
            "__doc__": doc,
            "default": default_val,
        })
    elif typ == "text_choice":
        choices = defn.get("choices", [])
        choices_info = f"Options: {', '.join(choices)}." if choices else "Any string value."
        doc = f"{description}. {choices_info}{mod_tag}"
        return type(f"ModOption_{key}", (TextChoice,), {
            "display_name": description,
            "__doc__": doc,
            "default": str(default),
        })
    elif typ == "range":
        range_start = int(defn.get("range_start", 0))
        range_end = int(defn.get("range_end", 100))
        try:
            default_val = int(default)
        except (ValueError, TypeError):
            default_val = range_start
        doc = f"{description}. Range: {range_start}–{range_end}.{mod_tag}"
        return type(f"ModOption_{key}", (Range,), {
            "display_name": description,
            "__doc__": doc,
            "range_start": range_start,
            "range_end": range_end,
            "default": default_val,
        })
    return None


def _register_dynamic_options() -> None:
    """Dynamically add mod-defined options to APFrameworkWorld.options_dataclass.

    Always runs, because capabilities_data must be added last (after goal and all mod
    options) so it appears at the bottom of the generated YAML.

    Also scans all *.yaml files in the Archipelago Players directory at import time.
    For each APFramework player YAML found, decodes capabilities_data and registers each
    mod-defined option (from option_defaults) as a proper Archipelago Option subclass.

    YAML field order produced: [static framework fields] → [goal] → [mod options] → [capabilities_data]

    Graceful fallback: if Players directory doesn't exist or decoding fails, only
    capabilities_data is appended. _build_option_values() Pass 2 still provides manifest
    defaults as a fallback for any options not registered here.
    """
    import os
    import glob
    import dataclasses
    from .Options import CapabilitiesData

    # Collect unique mod option definitions across all APFramework player YAMLs.
    # First definition seen wins — all mods using this APWorld should have consistent defaults.
    all_option_defs: dict = {}

    try:
        import yaml
        from Utils import user_path
        players_dir = user_path("Players")
        if os.path.exists(players_dir):
            for yaml_path in glob.glob(os.path.join(players_dir, "**", "*.yaml"), recursive=True):
                try:
                    with open(yaml_path, encoding="utf-8") as f:
                        content = yaml.safe_load(f)
                    if not isinstance(content, dict):
                        continue
                    apf_section = content.get("APFramework", {})
                    if not apf_section:
                        continue
                    caps_str = apf_section.get("capabilities_data", "")
                    if not caps_str:
                        continue
                    caps_json = json.loads(base64.b64decode(caps_str).decode("utf-8"))
                    for key, defn in caps_json.get("option_defaults", {}).items():
                        # Skip options already declared as static ClassVar fields
                        if key in APFrameworkOptions.__dataclass_fields__:
                            continue
                        if key not in all_option_defs:
                            all_option_defs[key] = defn
                except Exception:
                    pass  # Gracefully skip unparseable or unexpected YAMLs
    except (ImportError, Exception):
        pass  # Not running inside Archipelago, or Players scan failed

    # Build dynamic option fields from collected definitions
    dynamic_fields = []
    for key, defn in all_option_defs.items():
        mod_id = defn.get("mod_id", "")
        OptionClass = _make_option_class_from_defn(key, defn, mod_id)
        if OptionClass is not None:
            dynamic_fields.append(
                (key, OptionClass, dataclasses.field(default_factory=OptionClass))
            )

    # capabilities_data always goes last — it's a large base64 blob that players should
    # not need to read or edit, so it belongs at the bottom of the generated YAML.
    caps_field = (
        "capabilities_data",
        CapabilitiesData,
        dataclasses.field(default_factory=CapabilitiesData),
    )

    # Create a new options class as a subclass of APFrameworkOptions with the dynamic fields
    # followed by capabilities_data. Field order in YAML:
    #   [static framework fields (logic_mode ... goal)] → [mod options] → [capabilities_data]
    NewOptionsClass = dataclasses.make_dataclass(
        "APFrameworkOptions",
        dynamic_fields + [caps_field],
        bases=(APFrameworkOptions,),
    )
    APFrameworkWorld.options_dataclass = NewOptionsClass


_register_dynamic_options()
