"""
AP Framework World for Archipelago.

This is a template/base world for games using the AP Framework mod system.
It dynamically creates items and locations from a capabilities config
generated by the in-game framework and embedded in the YAML as base64.

To create a game-specific world:
1. Copy this directory to your Archipelago/worlds/<game_name> folder
2. Update the game name and other constants
3. Optionally override methods to add game-specific logic
"""

from typing import Dict, List, Any, ClassVar, Set
import base64
import json

from BaseClasses import Item, Location, Region, Tutorial, ItemClassification, MultiWorld
from worlds.AutoWorld import World, WebWorld

from .Items import APFrameworkItem, ItemData, build_item_table, get_filler_items, get_trap_items
from .Locations import APFrameworkLocation, LocationData, CountRequirement, build_location_table
from .Options import APFrameworkOptions
from .Rules import set_rules, set_completion_rules


class APFrameworkWebWorld(WebWorld):
    """Web world for displaying game info on the Archipelago website."""
    theme = "jungle"

    tutorials = [
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to setting up the AP Framework multiworld.",
            "English",
            "setup_en.md",
            "setup/en",
            ["AP Framework Team"]
        )
    ]


class APFrameworkWorld(World):
    """
    AP Framework World - A template for games using the AP Framework mod system.

    This world reads item and location definitions from a capabilities config
    embedded as base64 in the YAML, allowing any game with AP Framework
    mods to be randomized in Archipelago.
    """

    # =========================================================================
    # Class Variables - Override these in game-specific subclasses
    # =========================================================================

    game: ClassVar[str] = "APFramework"  # Change to your game's name
    web: ClassVar[WebWorld] = APFrameworkWebWorld()

    options_dataclass = APFrameworkOptions
    options: APFrameworkOptions

    # Topology: 0 = no logic, 1 = basic, 2 = advanced
    topology_present: ClassVar[bool] = False

    # =========================================================================
    # Instance Variables
    # =========================================================================

    item_table: Dict[str, ItemData]
    location_table: Dict[str, LocationData]
    region_table: Dict[str, Dict[str, Any]]  # region_name -> {requires_all, requires_any, requires_count, requires_option}
    capabilities: Dict[str, Any]
    id_remapping: Dict[int, int]

    # Item/Location name to ID mappings (required by Archipelago)
    item_name_to_id: ClassVar[Dict[str, int]] = {}
    location_name_to_id: ClassVar[Dict[str, int]] = {}

    # =========================================================================
    # Initialization
    # =========================================================================

    def __init__(self, multiworld: MultiWorld, player: int):
        super().__init__(multiworld, player)
        self.item_table = {}
        self.location_table = {}
        self.region_table = {}
        self.capabilities = {}
        self.id_remapping = {}

    # =========================================================================
    # World Generation
    # =========================================================================

    def generate_early(self) -> None:
        """
        Decode base64 capabilities data and set up item/location tables.
        Called before item/location creation.
        """
        cap_data = self.options.capabilities_data.value
        if not cap_data:
            raise Exception(
                f"[{self.game}] capabilities_data is required.\n"
                "Use the YAML file generated by the AP Framework, or manually "
                "base64-encode your AP_Capabilities JSON file."
            )

        try:
            decoded = base64.b64decode(cap_data).decode("utf-8")
            self.capabilities = self._process_capabilities(json.loads(decoded))
        except Exception as e:
            raise Exception(f"[{self.game}] Failed to decode capabilities_data: {e}")

        # Filter capabilities by requires_option before building tables
        self._filter_by_requires_option()

        # Build item and location tables
        self.item_table = build_item_table(self.capabilities)
        self.location_table = build_location_table(self.capabilities)

        # Build region table from capabilities
        self.region_table = self._build_region_table()

        # Set topology_present based on logic mode
        if self.options.logic_mode.value == 1 and self.region_table:  # basic
            self.__class__.topology_present = True

        # Update class-level ID mappings (required for item/location creation)
        self.__class__.item_name_to_id = {
            name: data.code for name, data in self.item_table.items()
        }
        self.__class__.location_name_to_id = {
            name: data.code for name, data in self.location_table.items()
        }

        # Check for ID conflicts with other worlds
        self.check_id_conflicts()

        # Update reverse mappings and network data package.
        # Archipelago snapshots the data package at module import time (when our
        # ClassVars are still {}). We must refresh it after populating the tables.
        self._update_data_package()

        # Diagnostic logging for data package debugging
        print(f"[APFramework DEBUG] generate_early complete:")
        print(f"  item_name_to_id ({len(self.__class__.item_name_to_id)} entries): "
              f"{dict(list(self.__class__.item_name_to_id.items())[:5])}")
        print(f"  location_name_to_id ({len(self.__class__.location_name_to_id)} entries): "
              f"{dict(list(self.__class__.location_name_to_id.items())[:5])}")
        print(f"  regions: {list(self.region_table.keys())}")
        print(f"  logic_mode: {'basic' if self.options.logic_mode.value == 1 else 'none'}")

    def _process_capabilities(self, data: dict) -> dict:
        """Unwrap nested structure and validate."""
        # The C++ framework nests locations/items/regions under a "capabilities" key
        if "capabilities" in data and isinstance(data["capabilities"], dict):
            caps = data["capabilities"]
            if "regions" in caps:
                data["regions"] = caps["regions"]
            if "locations" in caps:
                data["locations"] = caps["locations"]
            if "items" in caps:
                data["items"] = caps["items"]

        required = ["version", "game", "locations", "items", "checksum"]
        for field in required:
            if field not in data:
                raise ValueError(f"Missing required field: {field}")
        return data

    def _filter_by_requires_option(self) -> None:
        """Filter capabilities entries by requires_option against player's YAML options.

        Removes locations, items, and regions from self.capabilities that have a
        requires_option condition not satisfied by the player's chosen options.

        Condition formats:
        - "opt_name"         -> include if option is truthy (non-zero, non-empty, true)
        - "opt_name=value"   -> include if option equals the specific value
        """
        def _check_condition(condition: str) -> bool:
            if "=" in condition:
                opt_name, expected = condition.split("=", 1)
            else:
                opt_name = condition
                expected = None

            # Look up the option value from the player's options
            opt = getattr(self.options, opt_name, None)
            if opt is None:
                # Unknown option — include by default (no filtering)
                return True

            value = opt.value
            if expected is not None:
                # Exact match — compare as string (handles Choice display names and Range values)
                return str(value).lower() == expected.lower()
            else:
                # Truthy check
                return bool(value)

        def _filter_list(entries: list) -> list:
            result = []
            for entry in entries:
                condition = entry.get("requires_option", "")
                if not condition or _check_condition(condition):
                    result.append(entry)
            return result

        self.capabilities["locations"] = _filter_list(self.capabilities.get("locations", []))
        self.capabilities["items"] = _filter_list(self.capabilities.get("items", []))
        if "regions" in self.capabilities:
            self.capabilities["regions"] = _filter_list(self.capabilities.get("regions", []))

    def _build_region_table(self) -> Dict[str, Dict[str, Any]]:
        """Build region table from capabilities regions data.

        Returns:
            Dict mapping region name to requirement data:
            {
                "requires_all": [...],
                "requires_any": [...],
                "requires_count": [CountRequirement(...)],
            }
        """
        region_table: Dict[str, Dict[str, Any]] = {}

        for region_data in self.capabilities.get("regions", []):
            name = region_data["name"]
            requires_count_raw = region_data.get("requires_count", [])
            requires_count = [
                CountRequirement(item=rc["item"], count=rc.get("count", 1))
                for rc in requires_count_raw
            ]
            region_table[name] = {
                "requires_all": region_data.get("requires", []),
                "requires_any": region_data.get("requires_any", []),
                "requires_count": requires_count,
            }

        return region_table

    def _update_data_package(self) -> None:
        """Update reverse mappings and network data package.

        Archipelago builds the network data package at module import time from
        class-level item_name_to_id and location_name_to_id. Since this world
        populates those dynamically in generate_early(), we must update the
        pre-built data package to reflect the actual mappings.
        """
        # Update reverse mappings (used by Archipelago internals)
        self.__class__.item_id_to_name = {
            code: name for name, code in self.__class__.item_name_to_id.items()
        }
        self.__class__.location_id_to_name = {
            code: name for name, code in self.__class__.location_name_to_id.items()
        }

        # Rebuild and replace the pre-built network data package entry
        import worlds
        worlds.network_data_package["games"][self.game] = self.__class__.get_data_package_data()

        print(f"[APFramework DEBUG] Data package updated:")
        dp = worlds.network_data_package["games"][self.game]
        print(f"  items: {len(dp.get('item_name_to_id', {}))}, "
              f"locations: {len(dp.get('location_name_to_id', {}))}, "
              f"checksum: {dp.get('checksum', 'N/A')}")

    def check_id_conflicts(self) -> None:
        """Check for ID conflicts with other worlds and remap if necessary."""
        # Collect all IDs used by other worlds
        used_ids: Set[int] = set()

        for world in self.multiworld.worlds.values():
            if world.player == self.player:
                continue

            # Get location IDs
            for loc in world.multiworld.get_locations(world.player):
                if loc.address is not None:
                    used_ids.add(loc.address)

            # Get item IDs
            for item_name, item_id in getattr(world, "item_name_to_id", {}).items():
                if item_id is not None:
                    used_ids.add(item_id)

        # Check for conflicts
        my_location_ids = {data.code for data in self.location_table.values()}
        my_item_ids = {data.code for data in self.item_table.values()}
        my_ids = my_location_ids | my_item_ids

        conflicts = my_ids & used_ids

        if conflicts:
            self.remap_ids(conflicts, used_ids)

    def remap_ids(self, conflicting_ids: Set[int], all_used_ids: Set[int]) -> None:
        """Remap conflicting IDs to safe values."""
        # Find safe starting point
        all_my_ids = {data.code for data in self.item_table.values()}
        all_my_ids |= {data.code for data in self.location_table.values()}
        all_ids = all_used_ids | all_my_ids

        safe_start = max(all_ids) + 1000 if all_ids else self.capabilities.get("id_base", 6942067) + 100000

        # Build remapping
        remap: Dict[int, int] = {}
        for old_id in sorted(conflicting_ids):
            remap[old_id] = safe_start
            safe_start += 1

        self.id_remapping = remap

        # Apply remapping to location table (preserve all fields)
        new_location_table = {}
        for name, data in self.location_table.items():
            new_code = remap.get(data.code, data.code)
            new_location_table[name] = LocationData(
                code=new_code,
                name=data.name,
                mod_id=data.mod_id,
                instance=data.instance,
                region=data.region,
                requires_all=data.requires_all,
                requires_any=data.requires_any,
                requires_count=data.requires_count,
                requires_option=data.requires_option,
            )
        self.location_table = new_location_table

        # Apply remapping to item table (preserve all fields)
        new_item_table = {}
        for name, data in self.item_table.items():
            new_code = remap.get(data.code, data.code)
            new_item_table[name] = ItemData(
                code=new_code,
                name=data.name,
                classification=data.classification,
                mod_id=data.mod_id,
                count=data.count,
                requires_option=data.requires_option,
            )
        self.item_table = new_item_table

        # Update class-level mappings
        self.__class__.item_name_to_id = {
            name: data.code for name, data in self.item_table.items()
        }
        self.__class__.location_name_to_id = {
            name: data.code for name, data in self.location_table.items()
        }

        # Refresh data package with remapped IDs
        self._update_data_package()

    def create_regions(self) -> None:
        """Create regions and locations.

        When logic_mode is "basic" and regions are defined, creates proper regions
        with Menu connecting to all of them. Locations are placed into their
        designated regions. Locations without a declared region go into "Main".

        When logic_mode is "none" or no regions exist, all locations go into a
        single "Main" region (flat Sphere 0 behavior).
        """
        menu_region = Region("Menu", self.player, self.multiworld)
        self.multiworld.regions.append(menu_region)

        use_regions = (self.options.logic_mode.value == 1 and self.region_table)

        # Build region objects — always create "Main" as the default region
        regions: Dict[str, Region] = {}
        regions["Main"] = Region("Main", self.player, self.multiworld)

        if use_regions:
            for region_name in self.region_table:
                if region_name not in regions:
                    regions[region_name] = Region(region_name, self.player, self.multiworld)

        # Place locations into their target regions
        for loc_name, loc_data in self.location_table.items():
            target_region = loc_data.region if use_regions else "Main"

            # If the target region wasn't declared, create it on-the-fly
            if target_region not in regions:
                regions[target_region] = Region(target_region, self.player, self.multiworld)

            region = regions[target_region]
            location = APFrameworkLocation(
                self.player,
                loc_name,
                loc_data.code,
                region
            )
            region.locations.append(location)

        # Connect Menu to all regions (flat topology — item requirements enforce ordering)
        for region in regions.values():
            menu_region.connect(region)
            self.multiworld.regions.append(region)

    def create_item(self, name: str) -> APFrameworkItem:
        """Create an item by name. Required by Archipelago for pre-fill and similar."""
        item_data = self.item_table.get(name)
        if item_data:
            return APFrameworkItem(name, item_data.classification, item_data.code, self.player)
        return APFrameworkItem(name, ItemClassification.filler,
                               self.item_name_to_id.get(name, 0), self.player)

    def create_items(self) -> None:
        """Create items and add to item pool."""
        # Count total locations
        total_locations = len(self.location_table)

        # Create defined items first
        items_created = 0
        filler_item_names = []

        for item_name, item_data in self.item_table.items():
            if item_data.count == -1:
                # This is a filler item - save for later
                filler_item_names.append(item_name)
                continue

            # Create specified count of this item
            for _ in range(item_data.count):
                item = APFrameworkItem(
                    item_name,
                    item_data.classification,
                    item_data.code,
                    self.player
                )
                self.multiworld.itempool.append(item)
                items_created += 1

        # Fill remaining slots with filler items
        remaining = total_locations - items_created

        if remaining > 0 and filler_item_names:
            # Get trap chance
            trap_chance = self.options.trap_item_chance.value / 100.0
            trap_items = get_trap_items(self.item_table)

            import random
            for i in range(remaining):
                # Determine if this should be a trap
                if trap_items and random.random() < trap_chance:
                    item_name = random.choice(trap_items)
                else:
                    item_name = random.choice(filler_item_names)

                item_data = self.item_table[item_name]
                item = APFrameworkItem(
                    item_name,
                    item_data.classification,
                    item_data.code,
                    self.player
                )
                self.multiworld.itempool.append(item)

    def set_rules(self) -> None:
        """Set access rules for locations."""
        set_rules(self)
        set_completion_rules(self)

    def fill_slot_data(self) -> Dict[str, Any]:
        """Return data to be sent to the client."""
        slot_data = {"id_remapping": self.id_remapping}
        print(f"[APFramework DEBUG] fill_slot_data called:")
        print(f"  id_remapping: {self.id_remapping}")
        print(f"  item_name_to_id: {len(self.__class__.item_name_to_id)} entries")
        print(f"  location_name_to_id: {len(self.__class__.location_name_to_id)} entries")
        return slot_data

    def get_filler_item_name(self) -> str:
        """Get a random filler item name."""
        filler_items = get_filler_items(self.item_table)
        if filler_items:
            import random
            return random.choice(filler_items)
        # Fallback - return first item
        if self.item_table:
            return next(iter(self.item_table.keys()))
        return "Nothing"
