"""
Options for the AP Framework World.

This module defines the configuration options that can be set in the player's YAML file.
"""

from dataclasses import dataclass
from Options import PerGameCommonOptions, TextChoice, Toggle, Range


class CapabilitiesFile(TextChoice):
    """
    Path to the capabilities config file generated by the AP Framework.

    This file should be placed in the Archipelago/Players directory and contains
    the list of items and locations defined by the mods running in-game.

    Example: "AP_Capabilities_Player1.json"
    """
    display_name = "Capabilities File"
    default = ""


class ValidateChecksum(Toggle):
    """
    Whether to validate the capabilities checksum during connection.

    When enabled, the framework will verify that the mod configuration hasn't
    changed since generation. If the checksum doesn't match, connection will fail.

    Disable this only for testing or if you know what you're doing.
    """
    display_name = "Validate Checksum"
    default = True


class FillerItemWeight(Range):
    """
    Weight multiplier for filler items.

    Higher values will generate more filler items to fill extra locations.
    This is useful when you have more locations than useful items.
    """
    display_name = "Filler Item Weight"
    range_start = 1
    range_end = 10
    default = 1


class TrapItemChance(Range):
    """
    Percentage chance for filler items to become traps (if trap items are defined).

    0 = no traps, 100 = all filler becomes traps
    """
    display_name = "Trap Item Chance"
    range_start = 0
    range_end = 100
    default = 10


@dataclass
class APFrameworkOptions(PerGameCommonOptions):
    """Options dataclass for AP Framework worlds."""
    capabilities_file: CapabilitiesFile
    validate_checksum: ValidateChecksum
    filler_item_weight: FillerItemWeight
    trap_item_chance: TrapItemChance
