"""
APF Manager — entry point.

Run in development:
    python -m tools.apf_manager

Frozen (cx_Freeze):
    APFManager.exe
"""

import multiprocessing
from pathlib import Path


def _ensure_version_file() -> None:
    """Create __version__.py for source-mode launches if it doesn't exist yet.

    The file is gitignored and regenerated by setup.py at freeze time with real
    metadata. This fallback prevents the 'v?.?.? (dev)' title bar when running
    from source without having created the file manually.
    See docs/public/dev/dev_setup.md §7 for the canonical format.

    This function is only reachable via __main__.py, which is the source-mode
    entry point. The frozen entry point (apf_manager_entry.py) never calls this.
    """
    version_file = Path(__file__).parent / "__version__.py"
    if version_file.exists():
        return
    version_file.write_text(
        "# Local dev copy — gitignored. Edit __version__ here to bump the Manager\n"
        "# version before a release build. Do not edit other fields — setup.py\n"
        "# overwrites them at freeze time.\n"
        '__version__           = "0.0.0"\n'
        '__build_id__          = "dev"\n'
        '__is_dev__            = True\n'
        '__framework_version__ = "?"\n',
        encoding="utf-8",
    )


def main():
    import sys

    _ensure_version_file()

    # Strip app-specific flags from sys.argv BEFORE any Kivy import.
    # Kivy parses sys.argv at import time and will error on unknown flags.
    devtools_mode = "--devtools" in sys.argv
    if devtools_mode:
        sys.argv.remove("--devtools")

    # freeze_support() MUST be called before any Kivy import. The frozen
    # multiprocessing child process runs module-level code first; if Kivy is
    # imported at module level it initializes an SDL2 window before
    # freeze_support() can intercept and exit. Import APFManagerApp here so the
    # child process exits cleanly without ever touching Kivy.
    multiprocessing.freeze_support()
    from .core.views.app import APFManagerApp
    APFManagerApp(devtools_mode=devtools_mode).run()


if __name__ == "__main__":
    main()
