"""
Dynamically generates one WorldTestBase test class per fixture found in
APF_TEST_FIXTURES_DIR (or worlds/apf/test/fixtures/ for local dev).

Each fixture produces:
  - A base class (no extra options beyond capabilities_data)
  - One additional class per <stem>_<variant>.options.json file found alongside

No fixtures → no test classes → pytest collects 0 tests (not a failure).

Set APF_TEST_FIXTURES_DIR to a directory containing .json fixture files
generated by tools/scripts/gen_capabilities.py before running these tests.
"""

from .bases import APFrameworkTestBase, list_fixtures, list_option_variants


def _cls_name(stem: str, variant: str = "") -> str:
    safe = stem.replace("-", "_").replace(" ", "_").replace(".", "_")
    name = f"Test_{safe}"
    if variant:
        safe_v = variant.replace("-", "_").replace(" ", "_").replace(".", "_")
        name = f"{name}_{safe_v}"
    return name


for _stem, _caps_data in list_fixtures().items():
    # Base class — capabilities_data only
    globals()[_cls_name(_stem)] = type(
        _cls_name(_stem),
        (APFrameworkTestBase,),
        {"options": {"capabilities_data": _caps_data}},
    )

    # One class per option variant
    for _variant, _extra_opts in list_option_variants(_stem).items():
        globals()[_cls_name(_stem, _variant)] = type(
            _cls_name(_stem, _variant),
            (APFrameworkTestBase,),
            {"options": {"capabilities_data": _caps_data, **_extra_opts}},
        )
